# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Credibility Coalition Community
tagline:          'tag line'
description:      'la de dah'
url:              https://credibilitycoalition.org
baseurl:          /

author:
  name:           
  url:            https://twitter.com/credcoalition

paginate:         5

# Custom vars
version:

github:
  repo:           https://github.com/credcoalition/
